# Generated by Django 5.0.1 on 2024-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('ssd', 'SSD'), ('power_supply', 'Блок питания'), ('monitor', 'Монитор')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
