# Generated by Django 5.0.1 on 2024-11-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_in', '0002_tradeinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinrequest',
            name='selected_items',
            field=models.TextField(default='N/A'),
        ),
    ]
