# Generated by Django 5.0.1 on 2024-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='graphics_card',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='motherboard',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
