# Generated by Django 5.0.1 on 2024-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_laptop',
            field=models.BooleanField(default=False),
        ),
    ]
