# Generated by Django 5.0.1 on 2024-11-25 16:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('servicer', '0006_alter_part_category_alter_part_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicer.part'),
        ),
        migrations.AlterField(
            model_name='line',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
