# Generated by Django 5.0.1 on 2024-11-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_line_part_alter_line_price'),
        ('product', '0006_product_is_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
