# Generated by Django 5.0.1 on 2024-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_line_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
