# Generated by Django 5.0.1 on 2024-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('cooling', 'Система охлаждения'), ('ram', 'Оперативная память'), ('cpu', 'Процессор'), ('psu', 'Блок питания'), ('hdd', 'Жесткий диск'), ('ssd', 'SSD'), ('monitor', 'Монитор')], max_length=15),
        ),
    ]
