# Generated by Django 5.0.1 on 2024-11-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0003_servicer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicer',
        ),
    ]
