# Generated by Django 5.0.1 on 2024-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0005_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('pc', 'Для ПК')], max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('cooling', 'Система охлаждения'), ('ram', 'Оперативная память'), ('cpu', 'Процессор'), ('psu', 'Блок питания'), ('hdd', 'Жесткий диск'), ('ssd', 'SSD')], max_length=15),
        ),
    ]
