# Generated by Django 5.0.1 on 2024-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_payment_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='delivery_address',
            field=models.TextField(max_length=60, verbose_name='Адрес клиента'),
        ),
    ]
