# Generated by Django 5.0.1 on 2024-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_product_certificate_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_address',
            field=models.TextField(default='N/A', max_length=50, verbose_name='Адрес клиента'),
        ),
    ]
