# Generated by Django 5.0.1 on 2024-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_product_remove_payment_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Товар'),
        ),
    ]
