# Generated by Django 5.0.1 on 2024-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_remove_product_product_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Товар')),
            ],
        ),
    ]
