# Generated by Django 5.0.1 on 2024-12-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='item',
        ),
    ]
