# Generated by Django 5.0.1 on 2024-12-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_rename_title_product_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
