# Generated by Django 5.0.1 on 2024-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profileproduct_product_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='log',
            field=models.TextField(),
        ),
    ]
